### ISSUE TITLE
Novel dataset

### ISSUE THREAD

**Issue by preyasgarg** [DLangerr/dcgan-mnist-tensorflow#1]
I am not able to load my own images using torch.utils.dataset function

**Comment by DLangerr** [comment]
The code only works for images of the same size as the mnist dataset. (28x28x1) If you want to use different sizes you have to make changes to the code.

**Comment by preyasgarg** [comment]
is there any other method to send batches into data for training

**Comment by DLangerr** [comment]
I would recommend reading the torch.utils.dataset documentation, as it might work differently for pytorch.
